# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/tao12345666333/argo-cd-demo/argo-cd-demo
  newTag: fa5714f419b3d11dee6ac795e38356e9c3c439cb

resources:
- deployment.yaml
- service.yaml
